# Generated by Django 4.2.27 on 2026-01-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
